---
go_arch_map:
  i386: "386"
  i686: "386"
  x86: "386"
  x86_64: "amd64"
  aarch64: "arm64"
  armv5l: "armv5"
  armv6l: "armv6"
  armv7l: "armv7"

go_arch: "{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"

# File name of the Helm redistributable file
helm_redis_filename: "helm-v{{ helm_version }}-{{ ansible_system | lower }}-{{ go_arch }}.tar.gz"
