- name: Init Helm (client only)
  shell: helm init --client-only
  when: helm_version.split('.')[0] == 'v2'

- name: Add Helm chart repositories
  shell: helm repo add {{ item.name }} {{ item.url }}
  with_items: "{{ helm_repos }}"
