---
- name: Init Helm (client only) for current user
  shell: helm init --client-only
  when: helm_version.split('.')[0] == 'v2'

- name: Add Helm chart repositories for current user
  shell: helm repo add {{ helm_repo.name }} {{ helm_repo.url }}
  with_items: "{{ helm_repos }}"
  loop_control:
    loop_var: helm_repo

- name: Update helm repos
  shell: helm repo update
