---
- name: Get Helm sha256sum
  set_fact:
    helm_sha256sum: "{{ lookup('url', 'https://get.helm.sh/helm-{{ helm_version }}-{{ ansible_system | lower }}-{{ go_arch }}.tar.gz.sha256') }}"
  delegate_to: localhost
  become: false

- name: Download Helm package
  get_url:
    url: "https://get.helm.sh/helm-{{ helm_version }}-{{ ansible_system | lower }}-{{ go_arch }}.tar.gz"
    dest: "/tmp/helm-{{ helm_version }}-{{ ansible_system | lower }}-{{ go_arch }}.tar.gz"
    checksum: "sha256:{{ helm_sha256sum }}"
  retries: 3
  delay: 2
  register: result
  until: result is succeeded
  delegate_to: localhost
  become: false

- name: Unpack Helm package
  unarchive:
    src: "/tmp/helm-{{ helm_version }}-{{ ansible_system | lower }}-{{ go_arch }}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/{{ ansible_system | lower }}-{{ go_arch }}/helm"
  delegate_to: localhost
  become: false

- name: Create '/usr/local/bin' directory if it does not exist
  file:
    path: /usr/local/bin
    state: directory
    owner: root
    group: root
    mode: 0755
  become: true

- name: Copy Helm binary to '/usr/local/bin'
  copy:
    src: "/tmp/{{ ansible_system | lower }}-{{ go_arch }}/helm"
    dest: "/usr/local/bin/helm"
    owner: root
    group: root
    mode: 0755
  become: true
