---
- name: Get Helm sha256sum
  set_fact:
    helm_sha256sum: "{{ lookup('url', 'https://get.helm.sh/helm-{{ helm_version }}-{{ ansible_system | lower }}-{{ go_arch }}.tar.gz.sha256') }}"
  delegate_to: localhost
  become: false

- name: Download Helm
  get_url:
    url: "https://get.helm.sh/helm-{{ helm_version }}-{{ ansible_system | lower }}-{{ go_arch }}.tar.gz"
    dest: "/tmp/helm-{{ helm_version }}-{{ ansible_system | lower }}-{{ go_arch }}.tar.gz"
    checksum: "sha256:{{ helm_sha256sum }}"
  register: helm_download_package
  until: helm_download_package is succeeded
  retries: 3
  delay: 2
  delegate_to: localhost
  become: false

# - name: download Helm
#   get_url:
#     url: "{{ helm_mirror }}/{{ helm_redis_filename }}"
#     dest: "{{ helm_download_dir }}/{{ helm_redis_filename }}"
#     sha256sum: "{{ helm_sha256sum.content | b64decode | trim }}"
#     force: no
#     use_proxy: yes
#     validate_certs: yes
#     mode: "u=rw,go=r"
