---
- name: Create download directory
  file:
    dest: "{{ helm_download_dir }}"
    state: directory
    mode: "0755"

- name: Download Helm sha256sum
  get_url:
    url: "{{ helm_mirror }}/{{ helm_redis_filename }}.sha256"
    dest: "{{ helm_download_dir }}/{{ helm_redis_filename }}.sha256"

- name: Read Helm sha256sum
  slurp:
    src: "{{ helm_download_dir }}/{{ helm_redis_filename }}.sha256"
  register: helm_sha256sum

- name: Download Helm package
  get_url:
    url: "{{ helm_mirror }}/{{ helm_redis_filename }}"
    dest: "{{ helm_download_dir }}/{{ helm_redis_filename }}"
    checksum: "sha256:{{ helm_sha256sum.content | b64decode | trim }}"
  retries: 3
  delay: 2
  register: result
  until: result is succeeded

- name: Install unarchive module dependencies
  apt:
    name:
      - tar
      - unzip
      - gzip
    state: present
  become: true

- name: Unpack Helm package
  unarchive:
    src: "{{ helm_download_dir }}/{{ helm_redis_filename }}"
    dest: "{{ helm_download_dir }}"
    remote_src: true

- name: Create the Helm installation dir
  file:
    path: "{{ helm_install_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Copy Helm binary to installation dir
  copy:
    src: "{{ helm_download_dir }}/{{ ansible_system | lower }}-{{ go_arch }}/helm"
    dest: "{{ helm_install_dir }}/helm"
    remote_src: true
    mode: "0755"
  become: true

- name: Create Helm link
  file:
    src: "{{ helm_install_dir }}/helm"
    dest: "/usr/local/bin/helm"
    state: link
    owner: root
    group: root
    force: true
  when: helm_install_dir not in ansible_env.PATH.split(':')
  become: yes
