---
- name: Download Helm sha256sum
  get_url:
    url: "{{ helm_mirror }}/{{ helm_redis_filename }}.sha256"
    dest: "{{ helm_download_dir }}/{{ helm_redis_filename }}.sha256"
  become: true

- name: Read Helm sha256sum
  slurp:
    src: "{{ helm_download_dir }}/{{ helm_redis_filename }}.sha256"
  register: helm_sha256sum
  become: true

# - name: Get Helm sha256sum
#   set_fact:
#     helm_sha256sum: "{{ lookup('url', '{{ helm_mirror }}/{{ helm_redis_filename }}.sha256') }}"
#   become: true

- name: Download Helm
  get_url:
    url: "{{ helm_mirror }}/{{ helm_redis_filename }}"
    dest: "{{ helm_download_dir }}/{{ helm_redis_filename }}"
    checksum: "sha256:{{ helm_sha256sum.content | b64decode | trim }}"
  retries: 3
  delay: 2
  register: result
  until: result is succeeded
  become: true

- name: Create the Helm installation dir
  file:
    path: "{{ helm_install_dir }}"
    state: directory
    mode: "0755"
  become: true

- name: Install unarchive module dependencies
  apt:
    name:
      - tar
      - unzip
      - gzip
    state: present
  become: true

- name: Install Helm
  unarchive:
    src: "{{ helm_download_dir }}/{{ helm_redis_filename }}"
    remote_src: yes
    dest: "{{ helm_install_dir }}"
    extra_opts:
      - "--strip-components=1"
    owner: root
    group: root
    creates: "{{ helm_install_dir }}/helm"
  become: true

- name: Create Helm link
  file:
    src: "{{ helm_install_dir }}/helm"
    dest: "/usr/local/bin/helm"
    state: link
    owner: root
    group: root
  become: yes
