---
- import_tasks: preflight.yml

- name: Check wether Helm only can be upgraded
  fail:
    msg: Helm current version is {{ helm_current_version.stdout }}, want to install version is {{ helm_version }}. Helm only can be upgraded
  when:
    - helm_current_version.rc == 0
    #- helm_is_installed.stat.exists
    - helm_only_can_be_upgraded | bool
    - helm_current_version.stdout > ('v' + helm_version)

- name: Install Helm
  include_tasks: install.yml
  #when: (not helm_is_installed.stat.exists) or (helm_current_version.stdout != helm_version)
  when: (helm_current_version.rc != 0) or (helm_current_version.stdout != ('v' + helm_version))

- name: Add Helm repos
  include_tasks: add-repos.yml
  when: helm_add_repos_for_current_user | bool
