---
- import_tasks: preflight.yml

- name: Install Helm (helm major version can't smaller than current)
  include_tasks: install.yml
  when: (not helm_is_installed.stat.exists) or (helm_current_version.stdout != helm_version and helm_current_version.stdout.split('.')[0] <= helm_version.split('.')[0])

- name: Add Helm repos
  include_tasks: add-repos.yml
  when: add_helm_repos_for_current_user | bool
