---
- import_tasks: preflight.yml

- name: Check wether Helm only can be upgraded
  fail:
    msg: Helm current version is {{ helm_current_version }}, want to install version is {{ helm_version }}. Helm only can be upgraded
  when:
    - helm_current_version is defined
    - helm_only_can_be_upgraded | bool
    - helm_current_version is version(helm_version, '>')

- name: Install Helm
  include_tasks: install.yml
  when: (helm_current_version is not defined) or (helm_current_version != helm_version)

- name: Add Helm repos
  include_tasks: add-repos.yml
  when: helm_add_repos_for_current_user | bool
