---
- name: Get Helm latest release
  uri:
    url: "https://api.github.com/repos/helm/helm/releases/latest"
    method: GET
    return_content: true
    status_code: 200
    body_format: json
    validate_certs: false
  register: helm_latest_release
  until: helm_latest_release.status == 200
  retries: 3
  when: helm_version == "latest"

- name: Set Helm version to {{ helm_latest_release.json.tag_name }}
  set_fact:
    helm_version: "{{ helm_latest_release.json.tag_name }}"
  when: helm_version == "latest"

- name: Check if Helm is installed
  stat:
    path: "{{ helm_install_dir }}/helm"
  register: helm_is_installed

- name: Gather currently installed Helm version (if any)
  command: >
    {{ helm_install_dir }}/helm version --client --template '{{ if .Version }}{{ .Version }}{{ else }}{{ .Client.SemVer }}{{ end }}'
  changed_when: false
  register: helm_current_version
  when: helm_is_installed.stat.exists
